name: Generate Snake Game

on:
  # This will run every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Generates the snake game from a GitHub user contributions graph
      - name: Generate Snake
        uses: Platane/snk@v2.0.1
        with:
          # github user name
          github_user_name: siddharthdhodi05
          # output path
          output: dist/github-contribution-grid-snake.svg

      - name: Upload Snake Game
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist/github-contribution-grid-snake.svg
